runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- functions/node_modules/
- node_modules/

handlers:

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.*)
  static_files: \1
  upload: (.*)
  secure: always
